# Generated by Django 3.2 on 2021-04-21 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_verification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('passanger', 'passanger'), ('delivery', 'delivery'), ('driver', 'driver'), ('shipper', 'shipper')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('lookup', models.CharField(choices=[('passanger', 'passanger'), ('delivery', 'delivery'), ('driver', 'driver'), ('shipper', 'shipper')], max_length=20)),
                ('current_city', models.CharField(max_length=40)),
                ('amount', models.FloatField(default=0.0)),
                ('is_accepted', models.BooleanField(default=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
