# Generated by Django 3.2 on 2021-04-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_package_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='contact',
            field=models.CharField(max_length=10),
        ),
    ]
