# Generated by Django 3.2 on 2021-04-30 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('package', '0004_alter_package_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='contact',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='package',
            name='current_city',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='package',
            name='destination',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='package',
            name='lookup',
            field=models.CharField(blank=True, choices=[('passanger', 'passanger'), ('delivery', 'delivery'), ('driver', 'driver'), ('shipper', 'shipper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(blank=True, choices=[('passanger', 'passanger'), ('delivery', 'delivery'), ('driver', 'driver'), ('shipper', 'shipper')], max_length=20),
        ),
        migrations.AlterField(
            model_name='package',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PackageLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('longitude', models.CharField(max_length=13)),
                ('latitude', models.CharField(max_length=13)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='package.package')),
            ],
        ),
    ]
