# Generated by Django 3.2 on 2021-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_code',
            field=models.CharField(default='64CPBPEGDC', editable=False, max_length=10),
        ),
    ]
