# Generated by Django 3.2 on 2021-04-30 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_profile_unique_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='unique_code',
            field=models.CharField(default='5gHxr6hj5', max_length=10),
        ),
    ]
